{ lib
, stdenv
, stdenvNoCC
, fetchurl
, runtimeShell
, glibc
, gcc-unwrapped
}:

# Kimi Code CLI (`kimi`) — prebuilt Node SEA single-file binary from code.kimi.com.
# version + per-system hashes live in ./sources.json, regenerated by ./update.sh.
#
# glibc-only binary (upstream ships no musl). On Linux we don't patchelf the
# 150MB SEA binary — keep it intact in libexec and launch through the nix
# loader with --library-path, same pattern as droid-nix.

let
  sources = builtins.fromJSON (builtins.readFile ./sources.json);
  src' = sources.systems.${stdenv.hostPlatform.system}
    or (throw "kimi-code: unsupported system ${stdenv.hostPlatform.system}");
  loader = if stdenv.hostPlatform.isAarch64
    then "ld-linux-aarch64.so.1"
    else "ld-linux-x86-64.so.2";
in
stdenvNoCC.mkDerivation {
  pname = "kimi-code";
  version = sources.version;

  src = fetchurl {
    url = "https://code.kimi.com/kimi-code/binaries/${sources.version}/${src'.filename}";
    inherit (src') hash;
  };

  dontUnpack = true;

  installPhase = ''
    runHook preInstall
  '' + (if stdenv.isDarwin then ''
    install -Dm755 $src $out/bin/kimi
  '' else ''
    install -Dm755 $src $out/libexec/kimi
    mkdir -p $out/bin
    cat > $out/bin/kimi <<EOF
    #!${runtimeShell}
    export KIMI_CODE_NO_AUTO_UPDATE=1
    exec ${glibc}/lib/${loader} \
      --library-path ${lib.makeLibraryPath [ glibc gcc-unwrapped.lib ]} \
      $out/libexec/kimi "\$@"
    EOF
    chmod +x $out/bin/kimi
  '') + ''
    runHook postInstall
  '';

  meta = {
    description = "Kimi Code — Moonshot AI agentic coding CLI";
    homepage = "https://code.kimi.com";
    license = lib.licenses.unfree;
    mainProgram = "kimi";
    platforms = builtins.attrNames sources.systems;
  };
}
